import { create } from 'zustand'
import { persist } from 'zustand/middleware'

export type Language = 'en' | 'da'

interface LanguageStore {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

// Comprehensive translation object
const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.checkin': 'Check In/Out',
    'nav.schedule': 'Schedule',
    'nav.admin': 'Admin',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.welcome': 'Welcome back',
    'dashboard.stats.hoursToday': 'Hours Today',
    'dashboard.stats.weeklyHours': 'Weekly Hours',
    'dashboard.stats.thisMonth': 'This Month',
    'dashboard.stats.overtime': 'Overtime',
    'dashboard.upcomingShifts': 'Upcoming Shifts',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.noShifts': 'No upcoming shifts',
    'dashboard.viewAll': 'View All',
    
    // Check In/Out
    'checkin.title': 'Check In/Out',
    'checkin.checkIn': 'Check In',
    'checkin.checkOut': 'Check Out',
    'checkin.currentlyCheckedIn': 'Currently checked in since',
    'checkin.location': 'Location',
    'checkin.time': 'Time',
    'checkin.status': 'Status',
    'checkin.checkedIn': 'Checked In',
    'checkin.checkedOut': 'Checked Out',
    'checkin.notCheckedIn': 'Not Checked In',
    
    // Schedule
    'schedule.title': 'Schedule',
    'schedule.allSchedules': 'All Schedules',
    'schedule.mySchedule': 'My Schedule',
    'schedule.listView': 'List View',
    'schedule.calendarView': 'Calendar View',
    'schedule.allRoles': 'All Roles',
    'schedule.allStatus': 'All Status',
    'schedule.noShiftsFound': 'No shifts found',
    'schedule.tryAdjustingFilters': 'Try adjusting your filters or check back later.',
    'schedule.requestTimeOff': 'Request Time Off',
    'schedule.scheduled': 'Scheduled',
    'schedule.pending': 'Pending',
    'schedule.cancelled': 'Cancelled',
    'schedule.completed': 'Completed',
    'schedule.noShow': 'No Show',
    
    // Calendar
    'calendar.today': 'Today',
    'calendar.scheduled': 'Scheduled',
    'calendar.pending': 'Pending',
    'calendar.more': 'more',
    
    // Admin
    'admin.users': 'Users',
    'admin.shifts': 'Shifts',
    'admin.timeoff': 'Time Off',
    'admin.approvals': 'Approvals',
    'admin.settings': 'Settings',
    'admin.createUser': 'Create User',
    'admin.temporary': 'Temporary',
    'admin.permanent': 'Permanent',
    'admin.editUser': 'Edit User',
    'admin.deleteUser': 'Delete User',
    'admin.enable': 'Enable',
    'admin.disable': 'Disable',
    'admin.disabled': 'Disabled',
    'admin.confirmDelete': 'Are you sure you want to delete this user? This action cannot be undone.',
    'admin.userCreated': 'User created successfully!',
    'admin.userDeleted': 'User deleted successfully',
    'admin.userUpdated': 'User updated successfully',
    
    // User Management
    'users.temporary': 'Part-time',
    'users.permanent': 'Permanent',
    'users.createUser': 'Create User',
    'users.editUser': 'Edit User',
    'users.deleteUser': 'Delete User',
    'users.enable': 'Enable',
    'users.disable': 'Disable',
    'users.firstName': 'First Name',
    'users.lastName': 'Last Name',
    'users.email': 'Email',
    'users.role': 'Role',
    'users.status': 'Status',
    'users.phone': 'Phone',
    'users.hourlyRate': 'Hourly Rate',
    'users.employee': 'Employee',
    'users.manager': 'Manager',
    'users.admin': 'Admin',
    'users.active': 'Active',
    'users.inactive': 'Inactive',
    
    // Shift Management
    'shifts.management': 'Shift Management',
    'shifts.createShift': 'Create Shift',
    'shifts.editShift': 'Edit Shift',
    'shifts.cancelShift': 'Cancel Shift',
    'shifts.deleteShift': 'Delete Shift',
    'shifts.publish': 'Publish',
    'shifts.searchEmployees': 'Search employees or roles...',
    'shifts.allStatus': 'All Status',
    'shifts.allLocations': 'All Locations',
    'shifts.shifts': 'shifts',
    'shifts.selected': 'shift(s) selected',
    'shifts.deletedSuccessfully': 'shift(s) deleted successfully',
    'shifts.cancelled': 'shift(s) cancelled',
    'shifts.published': 'shift(s) published',
    'shifts.employee': 'Employee',
    'shifts.dateTime': 'Date & Time',
    'shifts.location': 'Location',
    'shifts.actions': 'Actions',
    'shifts.noShiftsFound': 'No shifts found',
    'shifts.tryAdjustingFilters': 'Try adjusting your filters or search terms.',
    'shifts.noShiftsCreated': 'No shifts have been created yet. Create your first shift to get started.',
    'shifts.totalShifts': 'Total Shifts',
    'shifts.thisWeek': 'This Week',
    'shifts.noShow': 'No Show',
    'shifts.shiftUpdated': 'Shift updated successfully',
    'shifts.shiftCreated': 'Shift created successfully',
    
    // Time Off
    'timeoff.management': 'Time Off Management',
    'timeoff.requestTimeOff': 'Request Time Off',
    'timeoff.approve': 'Approve',
    'timeoff.reject': 'Reject',
    'timeoff.pending': 'Pending',
    'timeoff.approved': 'Approved',
    'timeoff.rejected': 'Rejected',
    'timeoff.reason': 'Reason',
    'timeoff.startDate': 'Start Date',
    'timeoff.endDate': 'End Date',
    'timeoff.days': 'Days',
    'timeoff.submittedBy': 'Submitted by',
    'timeoff.submittedOn': 'Submitted on',
    'timeoff.reviewedBy': 'Reviewed by',
    'timeoff.reviewedOn': 'Reviewed on',
    'timeoff.noRequests': 'No time off requests found',
    'timeoff.onTimeOffUntil': 'Time off till',
    'timeoff.availabilityWarning': 'User is on time off until',
    
    // Forms
    'form.save': 'Save',
    'form.cancel': 'Cancel',
    'form.delete': 'Delete',
    'form.edit': 'Edit',
    'form.close': 'Close',
    'form.loading': 'Loading...',
    'form.submit': 'Submit',
    'form.reset': 'Reset',
    'form.confirm': 'Confirm',
    'form.back': 'Back',
    'form.next': 'Next',
    'form.previous': 'Previous',
    
    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.email': 'Email',
    'common.firstName': 'First Name',
    'common.lastName': 'Last Name',
    'common.role': 'Role',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.time': 'Time',
    'common.notes': 'Notes',
    'common.actions': 'Actions',
    'common.details': 'Details',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Information',
    
    // Login
    'login.title': 'Sign In',
    'login.username': 'Username',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.forgotPassword': 'Forgot Password?',
    'login.rememberMe': 'Remember Me',
    'login.invalidCredentials': 'Invalid username or password',
    
    // Messages
    'messages.operationFailed': 'Operation failed. Please try again.',
    'messages.operationSuccessful': 'Operation completed successfully.',
    'messages.confirmDelete': 'Are you sure you want to delete this item?',
    'messages.accessDenied': 'You don\'t have permission to perform this action.',
  },
  da: {
    // Navigation
    'nav.dashboard': 'Oversigt',
    'nav.checkin': 'Ind/Ud stempling',
    'nav.schedule': 'Vagtplan',
    'nav.admin': 'Administration',
    'nav.logout': 'Log ud',
    
    // Dashboard
    'dashboard.welcome': 'Velkommen tilbage',
    'dashboard.stats.hoursToday': 'Timer i dag',
    'dashboard.stats.weeklyHours': 'Ugentlige timer',
    'dashboard.stats.thisMonth': 'Denne måned',
    'dashboard.stats.overtime': 'Overarbejde',
    'dashboard.upcomingShifts': 'Kommende vagter',
    'dashboard.recentActivity': 'Seneste aktivitet',
    'dashboard.noShifts': 'Ingen kommende vagter',
    'dashboard.viewAll': 'Se alle',
    
    // Check In/Out
    'checkin.title': 'Ind/Ud stempling',
    'checkin.checkIn': 'Stempel ind',
    'checkin.checkOut': 'Stempel ud',
    'checkin.currentlyCheckedIn': 'Tjekket ind siden',
    'checkin.location': 'Lokation',
    'checkin.time': 'Tid',
    'checkin.status': 'Status',
    'checkin.checkedIn': 'Tjekket ind',
    'checkin.checkedOut': 'Tjekket ud',
    'checkin.notCheckedIn': 'Ikke tjekket ind',
    
    // Schedule
    'schedule.title': 'Vagtplan',
    'schedule.allSchedules': 'Alle vagtplaner',
    'schedule.mySchedule': 'Min vagtplan',
    'schedule.listView': 'Listevisning',
    'schedule.calendarView': 'Kalendervisning',
    'schedule.allRoles': 'Alle roller',
    'schedule.allStatus': 'Alle statusser',
    'schedule.noShiftsFound': 'Ingen vagter fundet',
    'schedule.tryAdjustingFilters': 'Prøv at justere dine filtre eller tjek tilbage senere.',
    'schedule.requestTimeOff': 'Anmod om fridage',
    'schedule.scheduled': 'Planlagt',
    'schedule.pending': 'Afventer',
    'schedule.cancelled': 'Aflyst',
    'schedule.completed': 'Afsluttet',
    'schedule.noShow': 'Ikke mødt op',
    
    // Calendar
    'calendar.today': 'I dag',
    'calendar.scheduled': 'Planlagt',
    'calendar.pending': 'Afventer',
    'calendar.more': 'flere',
    
    // Admin
    'admin.users': 'Brugere',
    'admin.shifts': 'Vagter',
    'admin.timeoff': 'Fridage',
    'admin.approvals': 'Godkendelser',
    'admin.settings': 'Indstillinger',
    'admin.createUser': 'Opret bruger',
    'admin.temporary': 'Midlertidig',
    'admin.permanent': 'Fast',
    'admin.editUser': 'Rediger bruger',
    'admin.deleteUser': 'Slet bruger',
    'admin.enable': 'Aktiver',
    'admin.disable': 'Deaktiver',
    'admin.disabled': 'Deaktiveret',
    'admin.confirmDelete': 'Er du sikker på, at du vil slette denne bruger? Denne handling kan ikke fortrydes.',
    'admin.userCreated': 'Bruger oprettet succesfuldt!',
    'admin.userDeleted': 'Bruger slettet succesfuldt',
    'admin.userUpdated': 'Bruger opdateret succesfuldt',
    
    // User Management
    'users.temporary': 'Deltid',
    'users.permanent': 'Fast ansættelse',
    'users.createUser': 'Opret bruger',
    'users.editUser': 'Rediger bruger',
    'users.deleteUser': 'Slet bruger',
    'users.enable': 'Aktiver',
    'users.disable': 'Deaktiver',
    'users.firstName': 'Fornavn',
    'users.lastName': 'Efternavn',
    'users.email': 'E-mail',
    'users.role': 'Rolle',
    'users.status': 'Status',
    'users.phone': 'Telefon',
    'users.hourlyRate': 'Timeløn',
    'users.employee': 'Medarbejder',
    'users.manager': 'Manager',
    'users.admin': 'Administrator',
    'users.active': 'Aktiv',
    'users.inactive': 'Inaktiv',
    
    // Shift Management
    'shifts.management': 'Vagtstyring',
    'shifts.createShift': 'Opret vagt',
    'shifts.editShift': 'Rediger vagt',
    'shifts.cancelShift': 'Aflys vagt',
    'shifts.deleteShift': 'Slet vagt',
    'shifts.publish': 'Publicer',
    'shifts.searchEmployees': 'Søg efter medarbejdere eller roller...',
    'shifts.allStatus': 'Alle statusser',
    'shifts.allLocations': 'Alle lokationer',
    'shifts.shifts': 'vagter',
    'shifts.selected': 'vagt(er) valgt',
    'shifts.deletedSuccessfully': 'vagt(er) slettet succesfuldt',
    'shifts.cancelled': 'vagt(er) aflyst',
    'shifts.published': 'vagt(er) publiceret',
    'shifts.employee': 'Medarbejder',
    'shifts.dateTime': 'Dato & Tid',
    'shifts.location': 'Lokation',
    'shifts.actions': 'Handlinger',
    'shifts.noShiftsFound': 'Ingen vagter fundet',
    'shifts.tryAdjustingFilters': 'Prøv at justere dine filtre eller søgetermer.',
    'shifts.noShiftsCreated': 'Der er endnu ikke oprettet vagter. Opret din første vagt for at komme i gang.',
    'shifts.totalShifts': 'Total vagter',
    'shifts.thisWeek': 'Denne uge',
    'shifts.noShow': 'Ikke mødt op',
    'shifts.shiftUpdated': 'Vagt opdateret succesfuldt',
    'shifts.shiftCreated': 'Vagt oprettet succesfuldt',
    
    // Time Off
    'timeoff.management': 'Fridagsstyring',
    'timeoff.requestTimeOff': 'Anmod om fridage',
    'timeoff.approve': 'Godkend',
    'timeoff.reject': 'Afvis',
    'timeoff.pending': 'Afventer',
    'timeoff.approved': 'Godkendt',
    'timeoff.rejected': 'Afvist',
    'timeoff.reason': 'Årsag',
    'timeoff.startDate': 'Startdato',
    'timeoff.endDate': 'Slutdato',
    'timeoff.days': 'Dage',
    'timeoff.submittedBy': 'Indsendt af',
    'timeoff.submittedOn': 'Indsendt den',
    'timeoff.reviewedBy': 'Gennemgået af',
    'timeoff.reviewedOn': 'Gennemgået den',
    'timeoff.noRequests': 'Ingen fridagsanmodninger fundet',
    'timeoff.onTimeOffUntil': 'Fridag til',
    'timeoff.availabilityWarning': 'Bruger har fridag til',
    
    // Forms
    'form.save': 'Gem',
    'form.cancel': 'Annuller',
    'form.delete': 'Slet',
    'form.edit': 'Rediger',
    'form.close': 'Luk',
    'form.loading': 'Indlæser...',
    'form.submit': 'Indsend',
    'form.reset': 'Nulstil',
    'form.confirm': 'Bekræft',
    'form.back': 'Tilbage',
    'form.next': 'Næste',
    'form.previous': 'Forrige',
    
    // Common
    'common.save': 'Gem',
    'common.cancel': 'Annuller',
    'common.delete': 'Slet',
    'common.edit': 'Rediger',
    'common.close': 'Luk',
    'common.loading': 'Indlæser...',
    'common.email': 'E-mail',
    'common.firstName': 'Fornavn',
    'common.lastName': 'Efternavn',
    'common.role': 'Rolle',
    'common.status': 'Status',
    'common.date': 'Dato',
    'common.time': 'Tid',
    'common.notes': 'Noter',
    'common.actions': 'Handlinger',
    'common.details': 'Detaljer',
    'common.yes': 'Ja',
    'common.no': 'Nej',
    'common.ok': 'OK',
    'common.error': 'Fejl',
    'common.success': 'Succes',
    'common.warning': 'Advarsel',
    'common.info': 'Information',
    
    // Login
    'login.title': 'Log ind',
    'login.username': 'Brugernavn',
    'login.password': 'Adgangskode',
    'login.signIn': 'Log ind',
    'login.forgotPassword': 'Glemt adgangskode?',
    'login.rememberMe': 'Husk mig',
    'login.invalidCredentials': 'Ugyldigt brugernavn eller adgangskode',
    
    // Messages
    'messages.operationFailed': 'Handling mislykkedes. Prøv venligst igen.',
    'messages.operationSuccessful': 'Handling gennemført succesfuldt.',
    'messages.confirmDelete': 'Er du sikker på, at du vil slette denne genstand?',
    'messages.accessDenied': 'Du har ikke tilladelse til at udføre denne handling.',
  }
}

export const useLanguageStore = create<LanguageStore>()(
  persist(
    (set, get) => ({
      language: 'en',
      
      setLanguage: (language: Language) => set({ language }),
      
      t: (key: string) => {
        const lang = get().language
        const translation = (translations as any)[lang][key]
        return translation || key
      },
    }),
    {
      name: 'timetidy-language',
    }
  )
) 